// src/utils/permissionUtils.ts


// src/permissions.ts

export const PERMISSION_CREATE_CLOCKRECORD = "PERMISSION_CREATE_CLOCKRECORD";
export const PERMISSION_READ_CLOCKRECORD = "PERMISSION_READ_CLOCKRECORD";
